package org.bloomclient.cosmetics;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import net.minecraft.client.render.OverlayTexture;
import net.minecraft.client.render.VertexConsumer;
import net.minecraft.client.util.math.MatrixStack;
import org.joml.Quaternionf;
import org.joml.Vector3f;

import java.util.ArrayList;
import java.util.List;

/** Immutable, render-ready version of Bloom's deliberately small cuboid format. */
public final class BloomHatMesh {
    private static final int MAX_CUBES = 512;
    private final List<Quad> quads;
    private final Animation animation;
    private final boolean hasWingCenter;
    private final boolean hasWingLeft;
    private final boolean hasWingRight;

    private BloomHatMesh(List<Quad> quads, Animation animation) {
        this.quads = List.copyOf(quads);
        this.animation = animation;
        this.hasWingCenter = quads.stream().anyMatch(quad -> quad.part == WingPart.CENTER);
        this.hasWingLeft = quads.stream().anyMatch(quad -> quad.part == WingPart.LEFT);
        this.hasWingRight = quads.stream().anyMatch(quad -> quad.part == WingPart.RIGHT);
    }

    public static BloomHatMesh parse(String source) {
        return parse(source, false);
    }

    /**
     * Wing cards are generated by the owner manager's Three.js preview. Its
     * north/south box faces map U in the opposite direction from Minecraft's
     * hand-authored quad order, so flat wing planes need their U coordinates
     * reversed to keep the inner roots and outer tips on the same sides.
     */
    public static BloomHatMesh parseWing(String source) {
        return parse(source, true);
    }

    private static BloomHatMesh parse(String source, boolean alignWingFacesWithPreview) {
        JsonObject root = JsonParser.parseString(source).getAsJsonObject();
        if (number(root, "formatVersion") != 1.0f) throw new IllegalArgumentException("Unsupported Bloom hat model");
        float textureWidth = positive(root, "textureWidth", 4096);
        float textureHeight = positive(root, "textureHeight", 4096);
        float uvWidth = positiveOrDefault(root, "uvWidth", textureWidth, 4096);
        float uvHeight = positiveOrDefault(root, "uvHeight", textureHeight, 4096);
        JsonArray cubes = root.getAsJsonArray("cubes");
        if (cubes == null || cubes.isEmpty() || cubes.size() > MAX_CUBES) throw new IllegalArgumentException("Invalid Bloom hat cube count");

        List<Quad> output = new ArrayList<>(cubes.size() * 6);
        for (JsonElement element : cubes) addCube(output, element.getAsJsonObject(), uvWidth, uvHeight, alignWingFacesWithPreview);
        if (output.isEmpty()) throw new IllegalArgumentException("Bloom hat model has no visible faces");
        return new BloomHatMesh(output, animation(root, alignWingFacesWithPreview));
    }

    public Animation animation() {
        return animation;
    }

    public boolean hasWingCenter() { return hasWingCenter; }
    public boolean hasWingLeft() { return hasWingLeft; }
    public boolean hasWingRight() { return hasWingRight; }

    public void render(MatrixStack.Entry entry, VertexConsumer consumer, int light) {
        render(entry, consumer, light, null);
    }

    public void renderWingCenter(MatrixStack.Entry entry, VertexConsumer consumer, int light) {
        render(entry, consumer, light, WingPart.CENTER);
    }

    public void renderWingLeft(MatrixStack.Entry entry, VertexConsumer consumer, int light) {
        render(entry, consumer, light, WingPart.LEFT);
    }

    public void renderWingRight(MatrixStack.Entry entry, VertexConsumer consumer, int light) {
        render(entry, consumer, light, WingPart.RIGHT);
    }

    private void render(MatrixStack.Entry entry, VertexConsumer consumer, int light, WingPart requestedPart) {
        for (Quad quad : quads) {
            if (requestedPart != null && quad.part != requestedPart) continue;
            for (Vertex vertex : quad.vertices) {
                consumer.vertex(entry, vertex.x, vertex.y, vertex.z)
                    .color(255, 255, 255, 255)
                    .texture(vertex.u, vertex.v)
                    .overlay(OverlayTexture.DEFAULT_UV)
                    .light(light)
                    .normal(entry, quad.normal.x, quad.normal.y, quad.normal.z);
            }
        }
    }

    private static void addCube(List<Quad> output, JsonObject cube, float textureWidth, float textureHeight,
                                boolean alignWingFacesWithPreview) {
        Vector3f from = vector(cube, "from");
        Vector3f to = vector(cube, "to");
        Vector3f pivot = vector(cube, "pivot");
        Vector3f rotation = vector(cube, "rotation");
        float x1 = Math.min(from.x, to.x) / 16.0f;
        float y1 = Math.min(from.y, to.y) / 16.0f;
        float z1 = Math.min(from.z, to.z) / 16.0f;
        float x2 = Math.max(from.x, to.x) / 16.0f;
        float y2 = Math.max(from.y, to.y) / 16.0f;
        float z2 = Math.max(from.z, to.z) / 16.0f;
        float centerX = (from.x + to.x) * 0.5f;
        WingPart wingPart = !alignWingFacesWithPreview || Math.abs(centerX) <= 0.01f
            ? WingPart.CENTER
            : centerX < 0 ? WingPart.LEFT : WingPart.RIGHT;
        Vector3f scaledPivot = new Vector3f(pivot).div(16.0f);
        Quaternionf transform = new Quaternionf().rotateZYX(
            (float) Math.toRadians(rotation.z),
            (float) Math.toRadians(rotation.y),
            (float) Math.toRadians(rotation.x)
        );
        JsonObject faces = cube.getAsJsonObject("faces");
        if (faces == null) return;

        addFace(output, faces, "east", textureWidth, textureHeight, false, wingPart, transform, scaledPivot, new Vector3f(1, 0, 0),
            point(x2, y1, z1), point(x2, y1, z2), point(x2, y2, z2), point(x2, y2, z1));
        addFace(output, faces, "west", textureWidth, textureHeight, false, wingPart, transform, scaledPivot, new Vector3f(-1, 0, 0),
            point(x1, y1, z2), point(x1, y1, z1), point(x1, y2, z1), point(x1, y2, z2));
        addFace(output, faces, "down", textureWidth, textureHeight, false, wingPart, transform, scaledPivot, new Vector3f(0, 1, 0),
            point(x1, y2, z1), point(x2, y2, z1), point(x2, y2, z2), point(x1, y2, z2));
        addFace(output, faces, "up", textureWidth, textureHeight, false, wingPart, transform, scaledPivot, new Vector3f(0, -1, 0),
            point(x1, y1, z2), point(x2, y1, z2), point(x2, y1, z1), point(x1, y1, z1));
        addFace(output, faces, "south", textureWidth, textureHeight, alignWingFacesWithPreview, wingPart, transform, scaledPivot, new Vector3f(0, 0, 1),
            point(x2, y1, z2), point(x1, y1, z2), point(x1, y2, z2), point(x2, y2, z2));
        addFace(output, faces, "north", textureWidth, textureHeight, alignWingFacesWithPreview, wingPart, transform, scaledPivot, new Vector3f(0, 0, -1),
            point(x1, y1, z1), point(x2, y1, z1), point(x2, y2, z1), point(x1, y2, z1));
    }

    private static void addFace(List<Quad> output, JsonObject faces, String name, float textureWidth, float textureHeight,
                                boolean reverseU, WingPart wingPart, Quaternionf rotation, Vector3f pivot, Vector3f normal, Vector3f... points) {
        JsonObject face = faces.has(name) && faces.get(name).isJsonObject() ? faces.getAsJsonObject(name) : null;
        if (face == null || !face.has("uv")) return;
        JsonArray uv = face.getAsJsonArray("uv");
        if (uv == null || uv.size() != 4) return;
        float u1 = uv.get(0).getAsFloat() / textureWidth;
        float v1 = uv.get(1).getAsFloat() / textureHeight;
        float u2 = uv.get(2).getAsFloat() / textureWidth;
        float v2 = uv.get(3).getAsFloat() / textureHeight;
        float[][] coords = reverseU
            ? new float[][]{{u2, v1}, {u1, v1}, {u1, v2}, {u2, v2}}
            : new float[][]{{u1, v1}, {u2, v1}, {u2, v2}, {u1, v2}};
        int turns = face.has("rotation") ? Math.floorMod(Math.round(face.get("rotation").getAsFloat() / 90.0f), 4) : 0;
        Vertex[] vertices = new Vertex[4];
        for (int index = 0; index < 4; index++) {
            Vector3f transformed = points[index].sub(pivot, new Vector3f());
            rotation.transform(transformed).add(pivot);
            int uvIndex = Math.floorMod(index - turns, 4);
            vertices[index] = new Vertex(transformed.x, transformed.y, transformed.z, coords[uvIndex][0], coords[uvIndex][1]);
        }
        Vector3f transformedNormal = rotation.transform(new Vector3f(normal)).normalize();
        output.add(new Quad(vertices, transformedNormal, wingPart));
    }

    private static Animation animation(JsonObject root, boolean wingModel) {
        if (!root.has("animation") || !root.get("animation").isJsonObject()) return Animation.NONE;
        JsonObject value = root.getAsJsonObject("animation");
        String type = value.has("type") && value.get("type").isJsonPrimitive()
            ? value.get("type").getAsString().toLowerCase()
            : "none";
        float speed = finiteOrDefault(value, "speed", 0.0f);
        if (!wingModel && type.equals("spin") && speed > 0) {
            return new Animation(AnimationType.SPIN, clamp(speed, 0.05f, 4.0f), 0.0f);
        }
        if (wingModel && type.equals("flap") && speed > 0) {
            float amplitude = clamp(finiteOrDefault(value, "amplitude", 18.0f), 1.0f, 60.0f);
            return new Animation(AnimationType.FLAP, clamp(speed, 0.05f, 4.0f), amplitude);
        }
        return Animation.NONE;
    }

    private static float finiteOrDefault(JsonObject object, String key, float fallback) {
        if (!object.has(key) || !object.get(key).isJsonPrimitive()) return fallback;
        try {
            float value = object.get(key).getAsFloat();
            return Float.isFinite(value) ? value : fallback;
        } catch (RuntimeException ignored) {
            return fallback;
        }
    }

    private static float clamp(float value, float minimum, float maximum) {
        return Math.max(minimum, Math.min(maximum, value));
    }

    private static float number(JsonObject object, String key) {
        return object.has(key) ? object.get(key).getAsFloat() : Float.NaN;
    }

    private static float positive(JsonObject object, String key, float maximum) {
        float value = number(object, key);
        if (!Float.isFinite(value) || value <= 0 || value > maximum) throw new IllegalArgumentException("Invalid " + key);
        return value;
    }

    private static float positiveOrDefault(JsonObject object, String key, float fallback, float maximum) {
        if (!object.has(key)) return fallback;
        return positive(object, key, maximum);
    }

    private static Vector3f vector(JsonObject object, String key) {
        JsonArray values = object.getAsJsonArray(key);
        if (values == null || values.size() != 3) throw new IllegalArgumentException("Invalid " + key);
        Vector3f result = new Vector3f(values.get(0).getAsFloat(), values.get(1).getAsFloat(), values.get(2).getAsFloat());
        if (!Float.isFinite(result.x) || !Float.isFinite(result.y) || !Float.isFinite(result.z)) throw new IllegalArgumentException("Invalid " + key);
        return result;
    }

    private static Vector3f point(float x, float y, float z) {
        return new Vector3f(x, y, z);
    }

    public enum AnimationType { NONE, SPIN, FLAP }
    public record Animation(AnimationType type, float speed, float amplitude) {
        private static final Animation NONE = new Animation(AnimationType.NONE, 0.0f, 0.0f);
    }
    private enum WingPart { CENTER, LEFT, RIGHT }
    private record Vertex(float x, float y, float z, float u, float v) {}
    private record Quad(Vertex[] vertices, Vector3f normal, WingPart part) {}
}
